//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public byte Codigo_Grupo { get; set; }
        public string Codigo_Curso { get; set; }
        public System.DateTime Fecha_Asistencia { get; set; }
        public string Tipo_Registro { get; set; }
        public string Tipo_ID_Esutiante { get; set; }
        public string Identificacion_Estudiante { get; set; }
    
        public virtual Matricula Matricula { get; set; }
    }
}
