//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correos_Profesores
    {
        public string Corre_Electronico { get; set; }
        public string Tipo_ID_Profesor { get; set; }
        public string Identificacion_Profesor { get; set; }
    
        public virtual Profesore Profesore { get; set; }
    }
}
