//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonos_Estudiantes
    {
        public string Numero_Telefono { get; set; }
        public string Tipo_ID_Estudiante { get; set; }
        public string Identificacion_Estudiante { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
    }
}
